CREATE TABLE `sap_real_estate_contract_contract_valuation_data`
(
  `InternalRealEstateNumber`        varchar(13) NOT NULL,
  `RETermNumber`                    varchar(4) NOT NULL,
  `ValidityStartEndDateValue`       varchar(16) NOT NULL,
  `RETermType`                      varchar(4) NOT NULL,
  `RETermName`                      varchar(60) DEFAULT NULL,
  `REValuationRule`                 varchar(10) DEFAULT NULL,
  `ValidityStartDate`               varchar(80) DEFAULT NULL,
  `ValidityEndDate`                 varchar(80) DEFAULT NULL,
  `REStatusObject`                  varchar(22) DEFAULT NULL,
  `RealEstateObjectType`            varchar(2) DEFAULT NULL,
  `REIdentification`                varchar(50) DEFAULT NULL,
  `ObjectValidFrom`                 varchar(80) DEFAULT NULL,
  `REConsiderationStartDate`        varchar(80) DEFAULT NULL,
  `RECashFlowPostingFromDate`       varchar(80) DEFAULT NULL,
  `REStatusObjectAsset`             varchar(22) DEFAULT NULL,
  `REValuationClassification`       varchar(1) DEFAULT NULL,
  `REInterestRate`                  varchar(17) DEFAULT NULL,
  `REFrequencyTerm`                 varchar(4) DEFAULT NULL,
  `REDistributionRule`              varchar(4) DEFAULT NULL,
  `REDistributionRuleParam1`        varchar(70) DEFAULT NULL,
  `REDistributionRuleParam2`        varchar(70) DEFAULT NULL,
  `REProbableEndDate`               varchar(80) DEFAULT NULL,
  `REAssetRightOfUseEndDate`        varchar(80) DEFAULT NULL,
  `REValuationRuleStatus`           varchar(1) DEFAULT NULL,
  `REValuationStatus`               varchar(1) DEFAULT NULL,
  `REValuationStatusReason`         varchar(1) DEFAULT NULL,
  `REValuationBehavior`             varchar(1) DEFAULT NULL,
  `RETaxType`                       varchar(4) DEFAULT NULL,
  `TaxGroup`                        varchar(20) DEFAULT NULL,
  `REAccountingObject`              varchar(22) DEFAULT NULL,
  `REInfoText`                      varchar(100) DEFAULT NULL,
  `REValuationFactorNumerator`      varchar(32) DEFAULT NULL,
  `REValuationFactorDenominator`    varchar(32) DEFAULT NULL,
  `REValuationCurrency`             varchar(3) DEFAULT NULL,
  `REValuationQuestionnaireUUID`    varchar(36) DEFAULT NULL,
  `Country`                         varchar(3) DEFAULT NULL,
    PRIMARY KEY (`InternalRealEstateNumber`, `RETermNumber`, `ValidityStartEndDateValue`, `RETermType`),
    CONSTRAINT `SAPRealEstateContractContractValuationData_fk` FOREIGN KEY (`InternalRealEstateNumber`) REFERENCES `sap_real_estate_contract_contract_data` (`InternalRealEstateNumber`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
