CREATE TABLE `sap_real_estate_contract_contract_notice_term_data`
(
  `InternalRealEstateNumber`          varchar(13) NOT NULL,
  `RETermType`                        varchar(4) NOT NULL,
  `RETermNumber`                      varchar(4) NOT NULL,
  `RENoticeRule`                      varchar(12) NOT NULL,
  `RENoticeSequenceNo`                varchar(4) NOT NULL,
  `RETermName`                        varchar(60) DEFAULT NULL,
  `RENoticeType`                      varchar(1) DEFAULT NULL,
  `RENoticeProcedure`                 varchar(4) DEFAULT NULL,
  `RENoticeGivingParty`               varchar(1) DEFAULT NULL,
  `RENoticeRuleType`                  varchar(1) DEFAULT NULL,
  `RENoticeRuleDescription`           varchar(60) DEFAULT NULL,
  `RETermPeriodInYears`               varchar(2) DEFAULT NULL,
  `RETermPeriodInMonths`              varchar(2) DEFAULT NULL,
  `RETermPeriodInDays`                varchar(2) DEFAULT NULL,
  `REPeriodEndRhythmType`             varchar(2) DEFAULT NULL,
  `RENoticePeriodInMonths`            varchar(2) DEFAULT NULL,
  `RENoticePeriodInWeeks`             varchar(2) DEFAULT NULL,
  `RENoticePeriodInDays`              varchar(2) DEFAULT NULL,
  `RENoticeGracePeriod`               varchar(2) DEFAULT NULL,
  `REGracePeriodCalOrWorkDays`        varchar(1) DEFAULT NULL,
  `RENoticePeriodCalendar`            varchar(2) DEFAULT NULL,
  `RENoticeYear`                      varchar(4) DEFAULT NULL,
  `RENoticeMonth`                     varchar(2) DEFAULT NULL,
  `RENoticeDay`                       varchar(2) DEFAULT NULL,
  `RENoticeReceiptYear`               varchar(4) DEFAULT NULL,
  `RENoticeReceiptMonth`              varchar(2) DEFAULT NULL,
  `RENoticeReceiptDay`                varchar(2) DEFAULT NULL,
  `RENoticeRcptCalOrWorkDays`         varchar(1) DEFAULT NULL,
  `RENoticeReceiptCalendar`           varchar(2) DEFAULT NULL,
    PRIMARY KEY (`InternalRealEstateNumber`, `RETermType`, `RETermNumber`, `RENoticeRule`, `RENoticeSequenceNo`),
    CONSTRAINT `SAPRealEstateContractContractNoticeTermData_fk` FOREIGN KEY (`InternalRealEstateNumber`) REFERENCES `sap_real_estate_contract_contract_data` (`InternalRealEstateNumber`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
