CREATE TABLE `sap_real_estate_contract_contract_condition_data`
(
  `InternalRealEstateNumber`          varchar(13) NOT NULL,
  `REConditionUUID`                   varchar(36) NOT NULL,
  `REStatusObjectCalculation`         varchar(22) NOT NULL,
  `REStatusObjectIDCalculation`       varchar(50) NOT NULL,
  `REConditionType`                   varchar(4) DEFAULT NULL,
  `REExtConditionPurpose`             varchar(4) DEFAULT NULL,
  `ValidityStartEndDateValue`         varchar(16) DEFAULT NULL,
  `ValidityStartDate`                 varchar(20) DEFAULT NULL,
  `REStatusObjectDistribution`        varchar(22) DEFAULT NULL,
  `REStatusObjectIDDistribution`      varchar(50) DEFAULT NULL,
  `REObjectTypeDistribution`          varchar(1) DEFAULT NULL,
  `REObjectTypePosting`               varchar(1) DEFAULT NULL,
  `ValidityEndDate`                   varchar(80) DEFAULT NULL,
  `CreationDateTime`                  varchar(80) DEFAULT NULL,
  `RESourceOfCreation`                varchar(10) DEFAULT NULL,
  `LastChangeDateTime`                varchar(80) DEFAULT NULL,
  `RESourceOfChange`                  varchar(10) DEFAULT NULL,
  `REIsOneTimeCondition`              tinyint(1) DEFAULT NULL,
  `REConditionIsStatistical`          tinyint(1) DEFAULT NULL,
  `REPostingTerm`                     varchar(4) DEFAULT NULL,
  `RERhythmTerm`                      varchar(4) DEFAULT NULL,
  `REAdjustmentNumber`                varchar(4) DEFAULT NULL,
  `REOrglAssignmentTerm`              varchar(4) DEFAULT NULL,
  `RESalesTerm`                       varchar(4) DEFAULT NULL,
  `REPeakSalesTerm`                   varchar(4) DEFAULT NULL,
  `RESrvcChrgSettlementPostingTrm`    varchar(4) DEFAULT NULL,
  `REWithholdingTaxTerm`              varchar(4) DEFAULT NULL,
  `RECalculationRule`                 varchar(4) DEFAULT NULL,
  `REUnitPrice`                       varchar(25) DEFAULT NULL,
  `REConditionCurrency`               varchar(3) DEFAULT NULL,
  `RECalculationRuleParam1`           varchar(70) DEFAULT NULL,
  `RECalculationRuleParam2`           varchar(70) DEFAULT NULL,
  `REDistributionRule`                varchar(4) DEFAULT NULL,
  `REDistributionRuleParam1`          varchar(70) DEFAULT NULL,
  `REDistributionRuleParam2`          varchar(70) DEFAULT NULL,
  `REReasonForChange`                 varchar(10) DEFAULT NULL,
  `REStsObjectParamCalculation`       varchar(22) DEFAULT NULL,
  `REStsObjectParamDistribution`      varchar(22) DEFAULT NULL,
    PRIMARY KEY (`InternalRealEstateNumber`, `REConditionUUID`, `REStatusObjectCalculation`, `REStatusObjectIDCalculation`),
    CONSTRAINT `SAPRealEstateContractContractConditionData_fk` FOREIGN KEY (`InternalRealEstateNumber`) REFERENCES `sap_real_estate_contract_contract_data` (`InternalRealEstateNumber`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
